model:
  vocab_size: 8192
  n_layers: 4                  
  n_heads: 6                     
  d_model: 384                
  d_ff: 1536                    
  max_seq_len: 512
  dropout: 0.3                 
